[package]
name = "huskarl-pingora"
version = "0.6.0"
edition = "2024"
rust-version = "1.92"
description = "Pingora integration for huskarl OAuth2 resource server."
repository = "https://github.com/huskarl-rs/huskarl-pingora"
homepage = "https://github.com/huskarl-rs/huskarl-pingora"
documentation = "https://docs.rs/huskarl-pingora"
license = "MIT OR Apache-2.0"
keywords = ["oauth2", "pingora", "security", "authentication"]
categories = ["authentication"]

[features]
default = ["resource", "login", "default-jws-verifier-platform"]
resource = ["dep:bon", "dep:huskarl-resource-server", "dep:matchit", "dep:pingora-core", "dep:serde_json"]
login = ["dep:bon", "dep:huskarl", "dep:huskarl-login", "dep:matchit", "dep:pingora-core"]
default-jws-verifier-platform = [
    "huskarl?/default-jws-verifier-platform",
    "huskarl-resource-server?/default-jws-verifier-platform",
]

[dependencies]
async-trait = "0.1.89"
bytes = "1"
http = "1"
log = "0.4"
pingora-proxy-delegate = "0.1"
pingora-error = "0.8"
pingora-http = "0.8"
pingora-proxy = { version = "0.8", default-features = false }
tokio = { version = "1", features = ["sync"] }

# resource feature
bon = { version = "3.9", optional = true }
huskarl-resource-server = { version = "0.8", default-features = false, optional = true }
matchit = { version = "0.9", optional = true }
pingora-core = { version = "0.8", default-features = false, optional = true }
serde_json = { version = "1", optional = true }

# login feature
huskarl = { version = "0.8", default-features = false, optional = true }
huskarl-login = { version = "0.3", optional = true }
pingora-cache = "0.8.0"

[dev-dependencies]
huskarl-resource-server = { version = "0.8" }
huskarl-reqwest = { version = "0.7", features = ["rustls-tls"] }
huskarl-crypto-native = { version = "0.8" }
hex = "0.4"
pingora-core = { version = "0.8", features = ["rustls"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
url = "2"
env_logger = "0.11"
rand = "0.10"
uuid = "1"

[[example]]
name = "jwt_proxy"
required-features = ["resource"]

[[example]]
name = "login_proxy"
required-features = ["login"]

[package.metadata.cargo-machete]
ignored = ["pingora-cache"]
